:rars_ecalls: footnote:[https://github.com/TheThirdOne/rars/wiki/Environment-Calls]

== Chapter 2: Environment Calls

We mentioned environment calls (aka ecalls, though they're also called system
calls or syscalls in other languages like MIPS) in chapter 0 when we were going
over our "Hello World" program, but what exactly are they?

Essentially, they are the built in functions of a operating system; in this case,
the simple operating system of the RISC-V simulators.  They provide access to all the
fundamental features, like input and output to/from both the console and files,
allocating memory, and exiting.  That covers the basics but RARS supports many more,
for things ranging from playing MIDI sounds, to getting a random number, to creating
GUI dialogs.{rars_ecalls}

.Basic RARS supported ecalls
[cols="3,1,6,6"]
|===
| Name | a7 | Arguments | Result

| print integer | 1 | a0 = integer to print |

| print float | 2 | fa0 = float to print |

| print double | 3 | fa0 = double to print |

| print string | 4 | a0 = address of string |

| read integer | 5 | | a0 = integer read

| read float | 6 | | fa0 = float read

| read double | 7 | | fa0 = double read

| read string | 8 | a0 = address of input buffer +
a1 = buffer size | works like C's fgets

| sbrk | 9 | a0 = size in bytes to allocate | a0 = address of allocated memory (sbrk is basically malloc but there is no free)

| exit | 10 | | program terminates

| print character | 11 | a0 = character to print (ascii value) |

| read character | 12 | | a0 = character read

| open file | 1024 | a0 = address of filename +
$a1 = flags | a0 = file descriptor (negative if error)

| lseek | 62 | a0 = file descriptor, a1 = offset from base, +
a2 = beginning(0), current(1), or end of the file(2) |
a0 = selected position from beginning of the file or -1 if error

| read from file | 63 | a0 = file descriptor +
a1 = address of input buffer +
a2 = max characters to read | a0 = number of characters read, -1 if error

| write to file | 64 | a0 = file descriptor +
a1 = address of output buffer +
a2 = number of characters to write | a0 = number of characters written

| close file | 57 | a0 = file descriptor |

| exit2 | 93 | a0 = termination result | program terminates, returning number in a0 (only meaningful when run in the terminal, ignored in GUI)

|===

As you can see, they really only cover the basics.  You can read or write the
different types, do file I/O using calls identical to POSIX functions
(open, read, write, close; see man pages), allocate memory, and exit.
Even so, they're sufficient to build anything you want.

So, what does that table mean?  How do these actually work?

The process is:

. Put the number for the ecall you want in `a7`
. Fill in the appropriate arguments, if any
. Execute the ecall with `ecall`

[source,riscv,linenums]
----
	li    a7, 1   # 1 is print integer
	li    a0, 42  # takes 1 arg in a0, the number to print
	ecall         # actually execute ecall
----

You can think of the above as `print_integer(42);`.  Let's look at an actual
program that uses a few more ecalls next.

=== Examples

[source,c,linenums]
----
#include <stdio.h>

int main()
{
	int age;
	int height;
	char name[50];
	printf("What's your name? ");
	fgets(name, 50, stdin);

	printf("Hello %s", name);

	printf("How old are you? ");
	scanf("%d", &age);

	printf("Enter your height in inches: ");
	scanf("%d", &height);

	printf("Your age + height = %d\n", age + height);

	return 0;
}
----

I'm using `fgets()` instead of `scanf("%s", name)` because fgets works the same as the
read string ecall (8).

[source,riscv,linenums]
----
.data

name:     .space 50

nameprompt:  .asciz "What's your name? "
hello_space: .asciz "Hello "
how_old:     .asciz "How old are you? "
ask_height:  .asciz "Enter your height in inches: "
ageplusheight: .asciz "Your age + height = "


.text
main:
	li    a7, 4      # print string
	la    a0, nameprompt  # load address of string to print into a7
	ecall

	li    a7, 8      # read string
	la    a0, name
	li    a1, 50
	ecall

	li    a7, 4
	la    a0, hello_space
	ecall

	la    a0, name  # note 4 is still in a7
	ecall

	# don't print a newline here because
	# one will be part of name unless they typed >48 characters

	li    a7, 4
	la    a0, how_old
	ecall

	li    a7, 5   # read integer
	ecall
	mv    t0, a0  # save age in t0

	li    a7, 4
	la    a0, ask_height
	ecall

	li    a7, 5   # read integer
	ecall
	add   t0, t0, a0 # t0 += height


	li    a7, 4
	la    a0, ageplusheight
	ecall

	li    a7, 1  # print int
	mv    a0, t0  # t0 = age + height
	ecall

	# print newline
	li    a7, 11   # print char
	li    a0, 10   # ascii value of '\n'
	ecall


	li    a7, 10     # exit ecall
	ecall
----

There a few things to note from the example.

We don't declare global variables for age or height.  We could, but there's no reason
to since we have to have them in registers to do the addition anyway.  Instead, we
copy/save age to `t0` so we can use `a0` for 2 more ecalls,
then add height to `t0`.

This is generally how it works.  Use registers for local variables unless
required to do otherwise.  We'll cover xref:ch5.adoc#_the_convention[more about]
register use when we cover the RISC-V calling convention.

Another thing is when we print their name, we don't put 4 in `a7` again because it
is still/already 4 from the lines above.

Lastly, many people will declare a string `"\n"` and use print string to print a newline,
but it's easier to use the print char ecall as we do right before exiting.



