
== Chapter 6: Floating Point Types

Up to this point we haven't really mentioned floating point values or instructions
at all, except how to declare them in the `.data` section and the ecalls for
reading and printing them.  There are two reasons we've left them alone till now.
First, they use a whole separate set of registers and instructions.  Second, and
partly because of the first reason, most college courses do not ever require
you to know or use floating point values.  Since this book is targeted at college
students, if you know you won't need to know this feel free to skip this chapter.

=== Floating Point Registers and Instructions

The greensheet contains all the floating point registers and their uses but you
can also see them in the table below:

.RISC-V Floating Point Registers and Uses
[cols="1,1,2,1"]
|===
| Register | Name     | Use                     | Preserved Across a Call

| f0-f7    | ft0-ft7  | Temporaries             | No

| f8-f9    | fs0-fs1  | Saved registers         | Yes

| f10-f11  | fa0-fa1  | Arguments/Return values | No

| f12-f17  | fa2-fa7  | Arguments               | No

| f18-f27  | fs2-fs11 | Saved registers         | Yes

| f28-f31  | ft8-ft11 | Temporaries             | Yes

|===

Likewise, you can look to the greensheet to see all the floating point instructions
but here are the most important/useful ones:

.RISC-V floating point instructions (and pseudoinstructions)
[cols="3,1,2m,2"]
|===
| Name | Opcode | Format | Operation

| Load | flw,fld | flw ft, n(rs)  | F[ft] = M[R[rs]+n]

| Store | fsw,fsd | fsw ft, n(rs)  | M[R[rs]+n] = F[ft]

| Move from Integer | fmv.[sd].x | fmv.s.x ft, rs | F[ft] = R[rs]

| Move to Integer | fmv.x.[sd] | fmv.x.s rs, ft | R[rs] = F[ft]

| Move | fmv.[sd] | fmv.s fd, fs | F[fd] = F[fs]

| Convert to SP from DP | fcvt.s.d | fcvt.s.d fd, fs | F[fd] = (float)F[fs]

| Convert to DP from SP | fcvt.d.s | fcvt.d.s fd, fs | F[fd] = (double)F[fs]

| Convert from 32b Integer | fcvt.[sd].w | fcvt.s.w fd, rs | F[fd] = (float)R[rs]

| Convert to 32b Integer | fcvt.w.[sd] | fcvt.w.s rd, fs | R[rd] = (int)F[fs]

| Compare Equal | feq.[sd] | feq.s rd, fs1, fs2 | R[rd] = (F[fs1] == F[fs2]) ? 1 : 0

| Compare Less Than | flt.[sd] | flt.s rd, fs1, fs2 | R[rd] = (F[fs1] < F[fs2]) ? 1 : 0

| Compare Less Than Equal | fle.[sd] | fle.s rd, fs1, fs2 | R[rd] = (F[fs1] <= F[fs2]) ? 1 : 0

| Absolute Value | fabs.[sd] | fabs.s fd, fs | F[fd] = (F[fs] < 0) ? -F[fs] : F[fs]

| Add | fadd.[sd] | fadd.s fd, fs, ft | F[fd] = F[fs] + F[ft]

| Subtract | fsub.[sd] | fsub.s fd, fs, ft | F[fd] = F[fs] - F[ft]

| Multiply | fmul.[sd] | fmul.s fd, fs, ft | F[fd] = F[fs] * F[ft]

| Divide | fdiv.[sd] | fdiv.s fd, fs, ft | F[fd] = F[fs] / F[ft]

| Negation | fneg.[sd] | fneg.s fd, fs | F[fd] = -F[fs]

|===

Anywhere you see a [sd], use s or d for single or double precisision.

You only get equal, less than, and less than equal, but it's easy enough to
flip the operands or test for the opposite result to cover the others.

=== Practice

We're going to briefly go over some of the more different aspects of dealing
with floating point numbers, but since most of it is the same but with a new
set of registers and calling convention, we won't be rehashing most concepts.

=== Getting Floating Point Literals

The first thing to know when dealing with floats is how to get float
(or double) literals into registers where you can actually operate on them.

There are two ways.  The first, and simpler way, is to declare them as globals
and then use the `flw` and `fld` instructions:


[source,riscv,linenums]
----
.data
a:     .float 3.14159
b:     .double 1.61

.text
main:

	la      t0, a
	flw     ft0, 0(t0)   # get a into ft0

	la      t0, b
	fld     ft1, 0(t0)   # get b into ft1

	# other code here
----

The second way is to use the regular registers and convert the values.  Of course
this means unless you want an integer value, you'd have to actually do it twice
and divide, and even that would limit you to rational numbers.  It looks like this:

[source,riscv,linenums]
----
	fmv.s.x   ft0, x0     # move 0 to ft0 (0 integer == 0.0 float)

	# get 4 to 4.0 in ft1
	li        t0, 4
	fcvt.s.w  ft1, t0     # ft1 = (float)t0
----

As you can see, other than 0 which is a special case, it requires at least 2
instructions.

NOTE: There is a 3rd way that is easier, but it's only supported in RARS, not Venus.
RARS lets you use `flw` and `fld` like this `flw   ft0, label, t0` where t0 is used as
a temporary, ie it's doing the load address into t0 for you before doing the actual flw


=== Branching

Branching based on floating point values is slightly different than normal.  Instead
of being able to test and jump in a single convenient instruction, you have to test
first and then jump in a second instruction if the test was true or not.  This is similar
to the way x86 and MIPS (for floats) do it.  For them, the test sets a special control/flag
register (or a certain bit or bits in the register) and then all jumps are based on its state.

With RISC-V there is no special control register.  The float comparisons are like the `slt`
instructions where you choose a destination register to set to 1 (true) or 0 (false).

Using them looks like this:

[source,riscv,linenums]
----
	flt.s    t0, ft0, ft1   # t0 = ft0 < ft1
	bne      t0, x0, was_less   # if (t0 != 0 aka ft0 < ft1) goto was_less

	# do something for ft0 >= ft1

	j       blah
was_less:
	
	# do something for ft0 < ft1

blah:
----

=== Functions

Finally, lets do a simple example of writing a function that takes a float and
returns a float.  I'm not going to bother doing one for doubles because it'd
be effectively the same, or doing one that requires the stack, because the only
differences from normal are a new set of registers and knowing which ones to save
or not from the table above.

So, how about a function to convert a fahrenheit temperature to celsius:

[source,riscv,linenums]
----
.data

# 5/9 = 0.5 with 5 repeating
fahrenheit2celsius: .float 0.5555555

.text
# float convert_F2C(float degrees_f)
convert_F2C:
	la       t0, fahrenheit2celsius
	flw      ft0, 0(t0)    # get conversion factor

	# C = (F - 32) * 5/9
	li       t0, 32
	fcvt.s.w ft1, t0       # convert to 32.0

	fsub.s   fa0, fa0, ft1  # fa0 = degrees_f - 32
	fmul.s   fa0, ft0, fa0  # fa0 = 0.555555 * fa0

	ret
----

You can see we follow the convention with the argument coming, and the result being
returned, in `fa0`.  In this function we use both methods for getting
a value into float registers; one we load from memory and the other, being
an integer, we convert directly.


=== Conclusion

As I said before, it is rare for courses to even bother covering floating point
instructions or assign any homework or projects that use them, but hopefully this
brief overview, combined with the knowledge of previous chapters is sufficient.

There are also 2 example programs
https://raw.githubusercontent.com/rswinkle/riscv_book/master/code/conversions.s[conversions.s]
and
https://raw.githubusercontent.com/rswinkle/riscv_book/master/code/calc_pi.s[calc_pi.s]
for you to study.


